### ISSUE TITLE
Handle HTTP2 GOAWAY

### ISSUE THREAD

**Issue by arnaldopereira** [itzmeanjan/ette#60]
This one might need a little investigating: sometimes ette receives GOAWAY from the node and handles that as any type of error. An example log message follows:

`Post "https://mainnet.infura.io/v3/x": http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error`

IMO ette shouldn't handle response errors generically, this might be the real issue here.

**Comment by itzmeanjan** [comment]
It's HTTP2's connection graceful termination initiated by server. Probably it rather than brining self down, connection retry can be attempted. 

What're your thoughts ?

**Comment by itzmeanjan** [comment]
I've stopped maintaining ette, so closing this issue. Thanks.
