### ISSUE TITLE
Failed to fetch block

### ISSUE THREAD

**Issue by simpsoncarlos3** [itzmeanjan/ette#63]
first of all, i would like to thank you for making ette. just like you i've been searching for a solution to query and subscribe to realtime data. thanks again

below is the error messages i'm getting right after i ran ./ette please help me with this

❗️ Failed to fetch block 3110474 : the method eth_getBlockByNumber does not exist/is not available

**Comment by simpsoncarlos3** [comment]
i figured out http is only accepting fully qualified domain name. it is not accepting localhost or http://127.0.0.1:8545
because my ethereum geth is in localhost

**Comment by itzmeanjan** [comment]
I've stopped maintaining ette, so closing this issue. Thanks.
