### ISSUE TITLE
Push real time notification to kafka

### ISSUE THREAD

**Issue by anujmax** [itzmeanjan/ette#66]
hi, 

Really impressive product and is exactly what I am looking for. Is there a way to push real time transcation notifications to kafka?

**Comment by itzmeanjan** [comment]
Hello, it can made to do so.

**Comment by hironate** [comment]
Seems like a really good product, just want to make sure, is it production ready. We are trying to build a marketplace and need to do lot of indexing.

**Comment by itzmeanjan** [comment]
I've stopped maintaining ette, so closing this issue. Thanks.
