### ISSUE TITLE
Failed to fetch block 14629780 : not found

### ISSUE THREAD

**Issue by dnzdlklc** [itzmeanjan/ette#67]
Thanks for this piece!

I'm running the code in real-time mode and I'm not able to get the blocks that are being created. Continuously seeing error: 

`Failed to fetch block 14629780 : not found`

Followed by: 

`Failed to fetch tx receipt [ block : 14629780 ] : not found`

The block number and hash is valid and I can see in my Alchemy provider results are returned in raw format.

Any ideas?

**Comment by itzmeanjan** [comment]
Hi,

I remember seeing this error, due to high concurrency factor sometimes the node doesn't ( or say fails to ) return certain block/ tx/ event log. High concurrency factor results into too many remote procedure calls sent to node.

**Comment by dnzdlklc** [comment]
Thanks, this seems to have solved it.

**Comment by itzmeanjan** [comment]
> Thanks, this seems to have solved it.

Yes, thanks to https://github.com/itzmeanjan/ette/pull/69
