### ISSUE TITLE
Failed to fetch block XX : not found

### ISSUE THREAD

**Issue by Gustbel** [itzmeanjan/ette#68]
Hello, I'm having this problem (`Failed to fetch block XX : not found`) in ALL the blocks when I put the configuration: `EtteMode=2` .
Blocks **can never be fetch** by the program.
I thought it was a concurrency issue but I've tried a local Ganache Blockchain and the exact same thing happens.
I leave you my `.env ` file:
```
RPCUrl=http://23.88.42.126:8545
WebsocketUrl=ws://23.88.42.126:8545
#RPCUrl=https://mainnet.infura.io/v3/025d7ebf96134012b954d0491f384c53
#WebsocketUrl=wss://mainnet.infura.io/ws/v3/025d7ebf96134012b954d0491f384c53
PORT=7000
DB_USER=postgres
DB_PASSWORD=mypassGUS
DB_HOST=127.0.0.1
DB_PORT=5432
DB_NAME=ette
RedisConnection=tcp
RedisAddress=127.0.0.1:6379
RedisPassword=mypassGUS
Domain=localhost
Production=yes
EtteMode=2
EtteGraphQLPlayGround=yes
ConcurrencyFactor=1
BlockConfirmations=0
BlockRange=1000
TimeRange=21600
SnapshotFile=snapshot.bin
```

Thank you

**Comment by Gustbel** [comment]
In Eth Mainnet with Infura:
![image](https://user-images.githubusercontent.com/44475146/165127775-e31697d9-361d-40a5-a424-3b29715af241.png)

In Ganache:
![Screenshot from 2022-04-25 13-02-42](https://user-images.githubusercontent.com/44475146/165128351-33182050-80a5-460d-b64c-f4a76784d8b5.png)

**Comment by itzmeanjan** [comment]
Interesting, https://github.com/itzmeanjan/ette/blob/6b2891dc2a130e400f76b818d5679c8c1e251197/app/block/fetch.go#L48 is getting triggered !

Looks like that node isn't returning block body, when requested over RPC !

Did you try using `curl` to request for that specific block from node ?

**Comment by Gustbel** [comment]
In both cases (Infura Eth Mainnet and Ganache) I receive the body block well using:
`curl -X POST -H "Content-Type: application/json" --data '{ "jsonrpc":"2.0", "method":"eth_getBlockByNumber", "params":["0xdf9c09", true ],"id":1 }' <rpc-url>`

That is precisely the problem for which I am writing you haha, apparently I see that the fetch problem is in 'ette', is it some misconfiguration on my part? I don't understand why I have such a basic error.
(I have tried on a VPS and the same thing happens to me).

**Comment by itzmeanjan** [comment]
> is it some misconfiguration on my part?

Your config file looks good to me. Did you try running on any other mode ( well EtteMode ) ?

**Comment by Gustbel** [comment]
thanks for your answer.
Here in `EtteMode=3`:
The problem seems to be fetch relatively new blocks for some reason.
The old blocks are fetch without problems for ette.
![Screenshot from 2022-04-26 12-53-15](https://user-images.githubusercontent.com/44475146/165342149-80cc311d-9e7b-4d87-bf8e-60e9c3f4d983.png)
![Screenshot from 2022-04-26 12-52-18](https://user-images.githubusercontent.com/44475146/165342162-253e2ded-6a8d-4ea5-98d4-77ec657cb92b.png)

**Comment by Gustbel** [comment]
But in Ganache, EtteMode=3 doesnt work either with recents blocks.
![Screenshot from 2022-04-26 12-24-26](https://user-images.githubusercontent.com/44475146/165347805-d1798e50-ffe3-42bd-85d4-825c107daee2.png)
And it's not a timestamp/timezone problem.
I don't know what else to try, if you could try it with Ganache I would appreciate it.

**Comment by itzmeanjan** [comment]
> But in Ganache, EtteMode=3 doesnt work either with recents blocks. ![Screenshot from 2022-04-26 12-24-26](https://user-images.githubusercontent.com/44475146/165347805-d1798e50-ffe3-42bd-85d4-825c107daee2.png) And it's not a timestamp/timezone problem. I don't know what else to try, if you could try it with Ganache I would appreciate it.

Actually I've never tried with ganache, I'll take a look.

**Comment by Gustbel** [comment]
I detected and solved the problem, Im preparing a PR.

**Comment by itzmeanjan** [comment]
> I detected and solved the problem, Im preparing a PR.

Thanks for the PR, just merged.

**Comment by itzmeanjan** [comment]
Here is a link to the PR which fixes the reported issue: https://github.com/itzmeanjan/ette/pull/69

**Comment by alvarogharo** [comment]
Having this same error. I've reduced the ConcurrencyFactor to 1 and also updated go-ethereum to latest version [v1.10.26].

![image](https://user-images.githubusercontent.com/32101141/211302583-6a8ce4f8-27c9-4f0a-9f47-73ab501dfa39.png)

All this blocks and transaction receipts can be obtained with curl to the same node.

**Comment by itzmeanjan** [comment]
Then it seems like it's failing to decode received data.
