### ISSUE TITLE
Cannot get past "Login"

### ISSUE THREAD

**Issue by Exlo84** [itzmeanjan/ette#71]
After signing the message with MetaMask, it does not go to dashboard, it only stays at the login screen.
How can i get past it. What might be wrong? Can i manually create APIkey, or disable the APIkey/metamask requirement?

**Comment by Gustbel** [comment]
Probably your `DOMAIN` (in .`env` file) is not the correct one.

If you are not running ette in local, change DOMAIN to the IP address where ette is running.
```Domain=XXX.XXX.XXX.XXX```

**Comment by Exlo84** [comment]
Thanks. That was it.
Rookie mistake

Domain was `localhost` which i changed to the actual local ip(192.168.1.xxx)
