### ISSUE TITLE
ette getting killed due to high memory usage

### ISSUE THREAD

**Issue by joeneldeasis** [itzmeanjan/ette#78]
Tried ette for indexing the polygon blockchain but ette is getting killed around block 79000 or 89000 due to high memory usage. This always happens to me a every time I clear the db and run a fresh start of ette.

Instance Specs:
```
ubuntu 22.04
4 cpu / 8 gb ram
```

ette config:
```
RPCUrl=http://172.x.x.x:8545
WebsocketUrl=wss://xxxxx
PORT=1337
DB_USER=admin
DB_PASSWORD=redacted
DB_HOST=localhost
DB_PORT=5432
DB_NAME=polygon
RedisConnection=tcp
RedisAddress=127.0.0.1:6379
RedisPassword=redacted
Domain=localhost
Production=yes
EtteMode=1
EtteGraphQLPlayGround=yes
ConcurrencyFactor=2
BlockConfirmations=100
BlockRange=100
TimeRange=21600
SnapshotFile=snapshot.bin
```

Instance free memory before ette hangs up and getting killed, on htop ette occupies 85%+ of memory
![image](https://user-images.githubusercontent.com/7831102/212009935-2356eb39-145d-49f3-9bec-7682f2173b65.png)

Ette getting killed at block 89431
![image](https://user-images.githubusercontent.com/7831102/212008719-7c0c1fb4-0a10-4eac-bc8f-8548847fef2d.png)

**Comment by itzmeanjan** [comment]
Yes possible. I'm not maintaining `ette` anymore.
